name: Lint

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  fix-lint-issues:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_KOTLIN: true
          DISABLE_ERRORS: true
          VALIDATE_BASH: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_CHECKOV: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_GITLEAKS: false
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: false
          VALIDATE_JSCPD: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_YAML: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_JAVA: false
      - name: Commit and push linting fixes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
